// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6ldWBMCeV5vcnmeRonX1tnzclJ3-VdPY',
    appId: '1:415157870144:web:a35ac6f758fce7013b09a5',
    messagingSenderId: '415157870144',
    projectId: 'my-project-schedule-6b277',
    authDomain: 'my-project-schedule-6b277.firebaseapp.com',
    storageBucket: 'my-project-schedule-6b277.firebasestorage.app',
    measurementId: 'G-0JLLW3M4DR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1QpvjPakM8efT6fxhj7mq5tCWy0X72Xg',
    appId: '1:415157870144:android:5ef993b66fbfb5d13b09a5',
    messagingSenderId: '415157870144',
    projectId: 'my-project-schedule-6b277',
    storageBucket: 'my-project-schedule-6b277.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6cYL6VKIwv-3t7XCU5_gxq07QvCD4o24',
    appId: '1:415157870144:ios:a549eb133f0b1d183b09a5',
    messagingSenderId: '415157870144',
    projectId: 'my-project-schedule-6b277',
    storageBucket: 'my-project-schedule-6b277.firebasestorage.app',
    iosBundleId: 'com.example.scheduleApp',
  );
}
